### ISSUE TITLE
Bot won't Disconnect

### ISSUE THREAD

**Issue by syncrotron** [JayStoll/BumblebeeBot#3]
When attempting to force the bot to disconnect (using both !disconnect and !leave), bumblebee bot would not leave. Another user used the !disconnect command and it worked fine.

Steps to reproduce:

1. Start bot
2. Use !join command (I used it in planning by mistake)
3. Got bot to !play something
4. Got bot to !pause (used experimental !skip, which had identical implementation to !pause)
5. Resumed with !play
6. Song played to completion
7. Stopped bot on cmd with ^C
8. Realized mistake and attempted to use both !disconnect and !leave, bot would print out "Disconnected" message without leaving.
9. Restarted bot without error.
10. Reattempted to use !leave, bot would print out "Disconnected" message without leaving.
11. Other developer used !leave command, bot disconnected immediately.

**Comment by JayStoll** [comment]
This is normal behavior, as when you restart the server a new instance of the bot is created
You must first:
!join then !leave and the bot will disconnect
